[general]
dateFormat = "yyyy-MM-dd HH-mm-ss"
outputFile = "{date} - {taskName}"

[vacuum]
enabled = true
time = 5
unit = "DAYS" # See java.time.temporal.ChronoUnit

[mysql]
enabled = true
database = "magento"
user = ""
password = ""

[filesystem]
enabled = true
targets = ["/home/magento/", "/home/test/test.ini"]


