[general]
dateFormat = "yyyy-MM-dd HH-mm-ss"
outputFile = "{date} - {taskName}"

[mysql]
enabled = true
database = "magento"
user = ""
password = ""

[filesystem]
enabled = true
targets = ["/home/magento/", "/home/test/test.ini"]


